liip_imagine:
    driver: "gd"
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360,230]
                    mode: outbound