#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# index:
#    path: /
#    controller: App\Controller\HomeController::index

# event:
#    path: /event
#    controller: App\Controller\HomeController::event